### ISSUE TITLE
Can HandyControls control language use the resx resource files within my project？

### ISSUE THREAD

**Issue by luluxiaoyu** [ghost1372/HandyControls#221]
I found in the document that introducing other language files requires additional installation of language packs. I hope Handycontrols control language can directly use the resource files within my project. I want to know if there is a way to implement it?

**Comment by ghost1372** [comment]
Hi @luluxiaoyu 
Yes, you can use directly.
We did this because we wanted to reduce the size of the final package.
You can put the language files next to the executable file and you will have no problem.
![image](https://github.com/ghost1372/HandyControls/assets/9213496/2097cd69-32d5-4d58-9475-3ffac6cc09e5)
